notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

env:
  - CC=gcc

language:
  - c

dist: trusty

addons:
  apt:
    packages:
      - build-essential
      - curl
      - libcurl4-openssl-dev
      - libssl-dev
      - nettle-dev
      - zlib1g-dev

install: true

script:
  - ./setup.sh ~/wtsi-opt

matrix:
  include:
    - #Trusty
      compiler: gcc
      os: linux
      sudo: required
    - #Trusty
      compiler: clang
      os: linux
      sudo: required
    - dist: xenial
      compiler: gcc
      os: linux
      sudo: required
    - dist: xenial
      compiler: clang
      os: linux
      sudo: required
